### ISSUE TITLE
Build Failure running 'mvn clean install'

### ISSUE THREAD

**Issue by jefferyvincent** [Adobe-Marketing-Cloud/aem-guides-wknd#57]
Hello, 

I am getting a build error, when I try and install. Here is my version:
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```
Here is the error:

```
[INFO] Reactor Summary for aem-guides-wknd 0.0.1-SNAPSHOT:
[INFO] 
[INFO] aem-guides-wknd .................................... SUCCESS [  0.199 s]
[INFO] WKND Sites Project - Core .......................... FAILURE [  1.109 s]
[INFO] WKND Sites Project - UI apps ....................... SKIPPED
[INFO] WKND Sites Project - UI content .................... SKIPPED
[INFO] WKND Sites Project - Integration Tests Bundles ..... SKIPPED
[INFO] WKND Sites Project - Integration Tests Launcher .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.691 s
[INFO] Finished at: 2019-02-25T15:01:42-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project aem-guides-wknd.core: Compilation failure: Compilation failure: 
[ERROR] /Users/jevinc/Projects/aem-guides-wknd/core/src/main/java/com/adobe/aem/guides/wknd/core/components/impl/BylineImpl.java:[6,24] package javax.annotation does not exist
[ERROR] /Users/jevinc/Projects/aem-guides-wknd/core/src/main/java/com/adobe/aem/guides/wknd/core/models/HelloWorldModel.java:[18,24] package javax.annotation does not exist
[ERROR] /Users/jevinc/Projects/aem-guides-wknd/core/src/main/java/com/adobe/aem/guides/wknd/core/components/impl/BylineImpl.java:[44,6] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: class com.adobe.aem.guides.wknd.core.components.impl.BylineImpl
[ERROR] /Users/jevinc/Projects/aem-guides-wknd/core/src/main/java/com/adobe/aem/guides/wknd/core/models/HelloWorldModel.java:[39,6] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: class com.adobe.aem.guides.wknd.core.models.HelloWorldModel
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aem-guides-wknd.core
ZADG4CJHD3:aem-guides-wknd jevinc$ 
```

**Comment by godanny86** [comment]
hi @jefferyvincent is this on the master branch? What version of Java are you on?

**Comment by jefferyvincent** [comment]
Hi @godanny86 yes this is on the master branch. I am using Java version: 11.0.1.

**Comment by godanny86** [comment]
Ah ok, for AEM code it needs to be compiled with Java 8: https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by jefferyvincent** [comment]
I am still not able to get to compile with Java 1.8:

`java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)`

mvn --version

`Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"`

**Comment by jefferyvincent** [comment]
Ok, I got it to compile. I used the wrong branch.
